### ISSUE TITLE
開発：OPサンプル

### ISSUE THREAD

**Issue by mkashimu** [shalloshallow/huritsu_game_ver2#2]
ミコトさんの書いてくれたやつ取り替えずうごかしてみるよー
エフェクトとかはまだつけないよー
文章量の感じをみてねー
- [x] 進捗　30 
- [x] 進捗　60 
- [ ] 進捗　100

**Comment by mkashimu** [comment]
https://github.com/shalloshallow/huritsu_game_ver2/releases/tag/0.0.0.1
ファイルを概ね全部　英数字にリネームしたのでそのままZIPでDLできるようになったよやったね
キャラ絵つけてません。  
一旦分量だけ見てもらえば…良いかな…

あとこのメンツなら
スクリプトファイル見せれば、シナリオの段階でよしなにやってくれそうなので晒しとくね
https://github.com/shalloshallow/huritsu_game_ver2/blob/giant/data/ks_scenario/0_0_op.ks

**Comment by mkashimu** [comment]
なんか微調整要望がきそうな気がするのでcloseしないで置いときます
まあサンプル微調整したとこでしょうがないんだけどね

**Comment by jme17561** [comment]
ウィンドウの縦横の文字数欲しいです！って言ったらなんとかなる？

**Comment by mkashimu** [comment]
あー。フォントによる。  
フォント決まればだいたいだせる。

ていうか時間見つけて一度くらい仮想頑張ってつけておくれ。

**Comment by jme17561** [comment]
仮想つけた結果、ちょいちょい改行が気になったので、質問しました。
だいたいあんなサイズに出るんだなあ、っていうのは把握した。
‥‥ので、詳細な字数出たら、それ参考にしつつ改行位置とかも微調整します。たぶん。

**Comment by mkashimu** [comment]
試してみた結果、
- MS P ゴシックのが見やすいかもしれないけど、英数字や記号の文字数管理できないのでMSゴシックで行きたいです。
- 基本19文字＋禁則処理文字×４行
- セリフ部分は4パターンから選んで下さい。ミコトさんの好みでいいよ。
1. 名前後改行なし、インデント無し
2. 名前後改行なし、インデント有り
3. 名前改行あり、インデント無し
4. 名前改行あり、インデント有り

![tewt01](https://cloud.githubusercontent.com/assets/6370514/4967865/ee735cf2-6828-11e4-8f1e-f291cc5f63e6.png)
![test02](https://cloud.githubusercontent.com/assets/6370514/4967867/eeab64a8-6828-11e4-957f-1cf2b07171f7.png)
![test03](https://cloud.githubusercontent.com/assets/6370514/4967866/eea79e4a-6828-11e4-9a70-8c36787d2b7a.png)
![test04](https://cloud.githubusercontent.com/assets/6370514/4967868/eeaf8c86-6828-11e4-9153-2f6eaa81fbf0.png)
