### ISSUE TITLE
TODO：フォント選択

### ISSUE THREAD

**Issue by mkashimu** [shalloshallow/huritsu_game_ver2#3]
明朝かゴシックかと フォントの色を、あとあと変更は聞くので
決めてもらえないだろうか
フォントはとりあえず直感で好きな方で良いよ

**Comment by mkashimu** [comment]
こういう感じで、確実にお返事欲しいものは作業ログページだけじゃなくてissueにしちゃったほうが良い気がします。かしこ。

**Comment by shalloshallow** [comment]
フォントは明朝に一票！
文字色は黒のままでいいと思います。

**Comment by mkashimu** [comment]
（たいとさんに依頼してたやつやねん）
（ISSUEは一応誰担当か設定できるます）

ご意見は皆さまから募集してるけど基本的にデザイナさんのご意見で決めるよん。

**Comment by Tait0** [comment]
![default](https://cloud.githubusercontent.com/assets/8873832/4809484/267f7490-5eac-11e4-84fd-28a1f168b8a1.jpg)
ゴシック（太字）

![default](https://cloud.githubusercontent.com/assets/8873832/4809493/416c2e6a-5eac-11e4-8c52-09fe9c42d691.jpg)
メイリオ（太字）
　  

---

以下、参考

![default](https://cloud.githubusercontent.com/assets/8873832/4809497/4f24aef6-5eac-11e4-8056-5f83ef039d56.jpg)
ゴジック（細字）

![default](https://cloud.githubusercontent.com/assets/8873832/4809513/67bacdd8-5eac-11e4-932a-7eb672255b41.jpg)
シャドウ

**Comment by Tait0** [comment]
・ゴシック：#333333
・袋文字：#ffffff （画像だと#ffeeeeになってるけど、普通に白でいいと思いますｽﾏﾝ）
・太字

個人的にはメイリオも捨てがたい。
（メイリオがパソコンに入ってない場合ってあるのかな教えて詳しい人）

文字色に真っ黒は使いたくない人なので微妙に灰色にしてます。
袋かシャドウがあった方が見やすい気がする。そして袋派。

少なくとも
・シャドウを使用するときは太字
・メイリオを使用するときは太字
は外さないといいかな。

明朝体はなぜか表示されなかった＆細くて見づらいイメージだったので除外したら
明朝派がいたので慌てた。

みんなの意見も聞きたいのでクローズは保留。

**Comment by mkashimu** [comment]
確認しましたー！ 私もゴシック派なのでゴシックで←  
メイリオもウィンドウズ限定だから多分大丈夫なはず。  
個人的にはちょっと可愛さが強い気がするのでゴシックと比べるならゴシックかなあ。

議論が活発なのは良いことだ（しみじみ）

**Comment by shalloshallow** [comment]
ここで物申す！
テキストの枠が鳥居で和風だから、明朝もかっこいいのではなかろうか！？

![mincho1](https://cloud.githubusercontent.com/assets/9385122/4810514/e3fda788-5eb3-11e4-8530-05d8667ff542.jpg)
ＭＳ 明朝（太字）/袋文字

![mincho 5](https://cloud.githubusercontent.com/assets/9385122/4810609/8e4bb522-5eb4-11e4-8f68-520e27ffdb9e.jpg)
ＭＳ 明朝（太字）/シャドウ

細字だとさらに細くなって読みづらかったので、太字のみ投稿。

と画像を上げてみたはいいものの、ゴシックより読みづらい感じが……。
ご意見求めます。よろしくお願いします。

**Comment by jme17561** [comment]
シャドウされると文字が読めないレベルで潰れるので、シャドウ無し希望。
(画像のシャドウ入り文字判読するのすら厳しい)
一番いいなって思ったのはメイリオだけど、プレーンのOSだけ買ったらメイリオって入ってないの？
(そんなマニアックなパソコンつかう人いるの？って気はするけど、自作とか想定する？？)
割と明朝が見やすいとかそんなことは‥‥

**Comment by mkashimu** [comment]
んー。  メイリオは普通入ってると思うんだけどなー。
は、置いといて、個人的には背景がシルエットでマットな質感なので、文字もマットな感じのが合うかなーとか思ったり思わなかったり。
割と割れたね。どーしようかなー
