### ISSUE TITLE
シナリオ：OP案

### ISSUE THREAD

**Issue by jme17561** [shalloshallow/huritsu_game_ver2#4]
- [x] 0-0
- [x] 0-1
- [x] 0-2
- [x] 0-3
- [x] 0-4
- [x] 0-5
- [x] 改行確認
- [x] 誤字脱字チェック

ここまでで一応完成
- [x] 改稿  
  必要に応じてやる

こっから先はフォント決まったらやる  
- [x] 字数合わせ
- [x] 改行位置決める
- [ ] 最終確認
  これでいいの？っていう確認とる  

ここまで終わったら小ネタ出し係に戻りますたぶん？  

OP案、感想、誤字報告、その他これ入れた方がいいよ、とか、コメント残していただければ適宜対応したいです。

**Comment by jme17561** [comment]
遅ればせながら、一通りの流れは作ってみました。
描写の重複、読みづらい、他、なにかあればコメント残していただけると助かります。

**Comment by mkashimu** [comment]
遅くなってすいませんーOP原稿さらっと確認しましたー
文量増えててありがたや…！
ぱっとみ問題ないと思いますが一応
OPサンプルの方に文字数の画像載せたので微調整したいとこあればおなしゃす！
https://github.com/shalloshallow/huritsu_game_ver2/issues/2

あと追って現在のシナリオでOP作り始めますーでき次第上げるね。
いやっほいやっと…やっと本番入れる…！

あとOPのファイルは基本これになります
https://github.com/shalloshallow/huritsu_game_ver2/blob/giant/data/ks_scenario/0_0_op.ks
ミコトさんなら、ブランチ管理の決まり事さえ覚えれば微調整なら自分で編集できる気がしなくもない。
